spring:
  application:
    name: mongo
  data:
    mongodb:
      uri: mongodb://root:hello@localhost:27017/mongodb?authSource=admin
  aop:
    auto: true
  sleuth:
    enabled: true
    web:
      servlet:
        enabled: true



profile:
  str: default

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]'
  level:
    com.profiler.profilerartifact.config.profiler.CustomPerformanceMonitorInterceptor: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG



profiling:
  pointcuts:
    com.example.mongo.mongo.services

sleuth:
  logging:
    pointcuts:
      com.example.mongo.mongo.services
